import { CatalogProduct } from './productsData';

/**
 * Curated product catalog ingested from FakeStoreAPI (20 products)
 * and DummyJSON (100 products). All prices converted to standard Indian Rupee (INR).
 */

export const FAKESTORE_PRODUCTS: CatalogProduct[] = [
  {
    id: 'prod_fs_1',
    name: 'Fjallraven Foldsack No. 1 Backpack (Fits 15" Laptop)',
    brand: 'Fjallraven',
    category: 'Peripherals',
    price: 934500,
    displayPrice: 9345,
    originalPrice: 11699,
    discountPercent: 20,
    rating: 3.9,
    reviewsCount: 960,
    inStock: true,
    stockCount: 35,
    badge: 'Trending',
    description: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve.',
    specs: ['Laptop Sleeve: Up to 15"', 'G-1000 HeavyDuty Eco Fabric', 'Volume: 16L', 'Water Resistant Finish'],
    imageUrl: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png',
    priceBand: 'premium',
    reviewSummary: 'Fjallraven Foldsack No. 1 Backpack is rated 3.9/5 by 960 customers. Great durable daily backpack with dedicated laptop sleeve.',
  },
  {
    id: 'prod_fs_2',
    name: 'Mens Casual Premium Slim Fit Henley T-Shirt',
    brand: 'UrbanCraft',
    category: 'Footwear',
    price: 189900,
    displayPrice: 1899,
    originalPrice: 2399,
    discountPercent: 21,
    rating: 4.1,
    reviewsCount: 2072,
    inStock: true,
    stockCount: 50,
    badge: 'Popular',
    description: 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, breathable and comfortable wearing.',
    specs: ['100% Breathable Cotton', 'Slim Fit Cut', 'Three-Button Henley Placket', 'Machine Washable'],
    imageUrl: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png',
    priceBand: 'budget',
    reviewSummary: 'Mens Casual Premium Slim Fit Henley is rated 4.1/5 by over 2,000 customers. Very comfortable everyday wear.',
  },
  {
    id: 'prod_fs_3',
    name: 'Mens Cotton Winter Outdoor Jacket',
    brand: 'Trailblazer',
    category: 'Footwear',
    price: 474900,
    displayPrice: 4749,
    originalPrice: 5999,
    discountPercent: 21,
    rating: 4.7,
    reviewsCount: 4000,
    inStock: true,
    stockCount: 28,
    badge: 'Top Rated',
    description: 'Great outerwear jacket for hiking, camping, cycling, and daily commute with multiple utility pockets.',
    specs: ['Heavy-Duty Cotton Shell', 'Fleece Thermal Lining', 'Multi-pocket Utility Design', 'Windproof Zipper'],
    imageUrl: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png',
    priceBand: 'mid',
    reviewSummary: 'Mens Cotton Winter Outdoor Jacket is top rated with 4.7/5 stars from 4,000 customers for warmth and rugged build.',
  },
  {
    id: 'prod_fs_5',
    name: "John Hardy Legends Naga Gold & Silver Station Dragon Bracelet",
    brand: 'John Hardy',
    category: 'Wearables',
    price: 5899900,
    displayPrice: 58999,
    originalPrice: 73999,
    discountPercent: 20,
    rating: 4.6,
    reviewsCount: 3200,
    inStock: true,
    stockCount: 10,
    badge: 'Luxury Pick',
    description: "From the Legends Collection, inspired by the mythical water dragon that protects the ocean's pearl.",
    specs: ['Sterling Silver & 18K Gold', 'Handcrafted Dragon Head Clasp', 'Authenticity Certificate Included', 'Luxury Velvet Box'],
    imageUrl: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png',
    priceBand: 'premium',
    reviewSummary: 'John Hardy Legends Naga Bracelet has 4.6/5 stars from 3,200 verified reviews. Outstanding craftsmanship and luxury finish.',
  },
  {
    id: 'prod_fs_6',
    name: 'Solid Gold Petite Micropave Diamond Ring',
    brand: 'Hafeez Center',
    category: 'Wearables',
    price: 1429900,
    displayPrice: 14299,
    originalPrice: 17999,
    discountPercent: 21,
    rating: 3.9,
    reviewsCount: 560,
    inStock: true,
    stockCount: 15,
    badge: 'Special Offer',
    description: 'Satisfaction Guaranteed. Elegant 14K solid gold petite micropave band encrusted with fine lab-grown diamonds.',
    specs: ['14K Solid Yellow Gold', '0.25ct Micropave Diamonds', 'High Polish Finish', 'Hallmarked Authenticity'],
    imageUrl: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png',
    priceBand: 'premium',
    reviewSummary: 'Solid Gold Petite Micropave Ring is rated 3.9/5 by 560 customers. Elegant and lightweight daily wear gold jewelry.',
  },
  {
    id: 'prod_fs_7',
    name: 'White Gold Plated Princess Solitaire Diamond Promise Ring',
    brand: 'SilverElegance',
    category: 'Wearables',
    price: 84900,
    displayPrice: 849,
    originalPrice: 1199,
    discountPercent: 29,
    rating: 3.0,
    reviewsCount: 3200,
    inStock: true,
    stockCount: 75,
    badge: 'Budget Pick',
    description: 'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Ideal gift for anniversaries and birthdays.',
    specs: ['18K White Gold Plating', 'Cubic Zirconia Solitaire Stone', 'Hypoallergenic Base', 'Velvet Gift Pouch'],
    imageUrl: 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png',
    priceBand: 'budget',
    reviewSummary: 'White Gold Plated Princess Ring has 3.0/5 stars. Affordable gift option with attractive sparkle.',
  },
  {
    id: 'prod_fs_9',
    name: 'WD 2TB Elements Portable External Hard Drive USB 3.0',
    brand: 'Western Digital',
    category: 'Storage',
    price: 549900,
    displayPrice: 5499,
    originalPrice: 6999,
    discountPercent: 21,
    rating: 4.5,
    reviewsCount: 1624,
    inStock: true,
    stockCount: 60,
    badge: 'Best Seller',
    description: 'High capacity storage in a compact design. Fast data transfers with USB 3.0 and USB 2.0 compatibility.',
    specs: ['2TB Storage Capacity', 'USB 3.0 High-Speed Transfer', 'Plug and Play for Windows/Mac', 'Shock-Resistant Enclosure'],
    imageUrl: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png',
    priceBand: 'mid',
    reviewSummary: 'WD 2TB Elements External Hard Drive is rated 4.5/5 by over 1,600 users. Reliable, quiet, and fast portable backup drive.',
  },
  {
    id: 'prod_fs_10',
    name: 'SanDisk SSD PLUS 1TB SATA III 2.5" Internal SSD (535MB/s)',
    brand: 'SanDisk',
    category: 'Storage',
    price: 924900,
    displayPrice: 9249,
    originalPrice: 11999,
    discountPercent: 23,
    rating: 4.6,
    reviewsCount: 3760,
    inStock: true,
    stockCount: 40,
    badge: 'Best Seller',
    description: 'Easy upgrade for faster boot up, shutdown, application load and response with speeds up to 535MB/s.',
    specs: ['1TB SATA III 6 Gb/s', 'Sequential Read: Up to 535 MB/s', 'Sequential Write: Up to 450 MB/s', 'Dashboard Health Monitoring'],
    imageUrl: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png',
    priceBand: 'premium',
    reviewSummary: 'SanDisk SSD PLUS 1TB is highly rated with 4.6/5 stars from 3,700 reviews for blazing boot speeds and durability.',
  },
  {
    id: 'prod_fs_11',
    name: 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache SATA III',
    brand: 'Silicon Power',
    category: 'Storage',
    price: 249900,
    displayPrice: 2499,
    originalPrice: 3299,
    discountPercent: 24,
    rating: 4.8,
    reviewsCount: 2552,
    inStock: true,
    stockCount: 55,
    badge: 'Top Rated',
    description: '3D NAND flash applied to deliver high transfer speeds and improved overall PC performance with SLC cache.',
    specs: ['256GB Capacity', '7mm Slim Design for Laptops', 'TRIM & Garbage Collection', 'ECC Error Correction'],
    imageUrl: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png',
    priceBand: 'mid',
    reviewSummary: 'Silicon Power 256GB SSD is top rated with 4.8/5 stars from 2,500 reviews as an unbeatable value boot drive upgrade.',
  },
  {
    id: 'prod_fs_12',
    name: 'WD 4TB Gaming Drive Works with PS4/PS5 & PC USB 3.0',
    brand: 'Western Digital',
    category: 'Gaming',
    price: 969900,
    displayPrice: 9699,
    originalPrice: 12499,
    discountPercent: 22,
    rating: 4.8,
    reviewsCount: 3200,
    inStock: true,
    stockCount: 30,
    badge: 'Top Rated',
    description: 'Expand your console and PC gaming library with 4TB capacity. Fast, portable setup with blue LED trim.',
    specs: ['4TB Massive Game Capacity', 'Compatible with PS4, PS5 & PC', 'USB 3.0 SuperSpeed', '3-Year Limited Warranty'],
    imageUrl: 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png',
    priceBand: 'premium',
    reviewSummary: 'WD 4TB Gaming Drive has 4.8/5 stars from 3,200 gamers. Holds 100+ AAA games seamlessly with zero lag.',
  },
  {
    id: 'prod_fs_13',
    name: 'Acer SB220Q 21.5" Full HD 1080p IPS Ultra-Thin 75Hz Monitor',
    brand: 'Acer',
    category: 'Peripherals',
    price: 899900,
    displayPrice: 8999,
    originalPrice: 11999,
    discountPercent: 25,
    rating: 4.4,
    reviewsCount: 2000,
    inStock: true,
    stockCount: 20,
    badge: 'Trending',
    description: '21.5 inches Full HD IPS display with AMD Radeon FreeSync, zero-frame ultra-thin bezel, and 75Hz refresh rate.',
    specs: ['1920 x 1080 IPS Panel', '75Hz Refresh Rate with FreeSync', '4ms Response Time', 'HDMI & VGA Connectivity'],
    imageUrl: 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png',
    priceBand: 'premium',
    reviewSummary: 'Acer SB220Q 21.5" IPS Monitor is rated 4.4/5 by 2,000 customers. Beautiful color accuracy and ultra-slim bezels for office and light gaming.',
  },
  {
    id: 'prod_fs_14',
    name: 'Samsung 49-Inch CHG90 144Hz 32:9 Curved QLED Gaming Monitor',
    brand: 'Samsung',
    category: 'Gaming',
    price: 8499900,
    displayPrice: 84999,
    originalPrice: 99999,
    discountPercent: 15,
    rating: 4.7,
    reviewsCount: 1120,
    inStock: true,
    stockCount: 8,
    badge: 'Flagship Beast',
    description: '49-inch super ultrawide 32:9 curved gaming monitor equivalent to two 27-inch displays side by side with Quantum Dot QLED.',
    specs: ['49" 32:9 Super Ultrawide', '144Hz Refresh Rate & 1ms MPRT', 'Quantum Dot QLED with HDR600', 'AMD FreeSync 2 Support'],
    imageUrl: 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png',
    priceBand: 'premium',
    reviewSummary: 'Samsung 49" CHG90 Ultrawide QLED Monitor is rated 4.7/5 stars. Unmatched immersive cockpit gaming and multi-window productivity.',
  },
  {
    id: 'prod_fs_15',
    name: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Waterproof Winter Coat",
    brand: 'BIYLACLESEN',
    category: 'Footwear',
    price: 484900,
    displayPrice: 4849,
    originalPrice: 6299,
    discountPercent: 23,
    rating: 4.2,
    reviewsCount: 1880,
    inStock: true,
    stockCount: 22,
    badge: 'Winter Special',
    description: '3-in-1 functional winter coat with detachable fleece inner layer and waterproof breathable outer shell.',
    specs: ['Waterproof & Windproof Outer', 'Detachable Thermal Fleece Liner', 'Adjustable Hood & Storm Cuffs', 'Zippered Security Pockets'],
    imageUrl: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png',
    priceBand: 'mid',
    reviewSummary: 'BIYLACLESEN 3-in-1 Winter Coat is rated 4.2/5 by 1,880 buyers. Highly versatile for freezing climates and ski trips.',
  },
  {
    id: 'prod_fs_16',
    name: "Lock and Love Women's Removable Hooded Faux Leather Biker Jacket",
    brand: 'Lock and Love',
    category: 'Footwear',
    price: 254900,
    displayPrice: 2549,
    originalPrice: 3499,
    discountPercent: 27,
    rating: 4.3,
    reviewsCount: 2720,
    inStock: true,
    stockCount: 30,
    badge: 'Trending',
    description: 'Stylish 2-for-1 hooded faux leather moto jacket with zippered front and detailed waist stitching.',
    specs: ['Premium Polyurethane Faux Leather', 'Removable Knit Hood with Drawstring', 'Dual Front Zip Pockets', 'Slim Tailored Fit'],
    imageUrl: 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png',
    priceBand: 'mid',
    reviewSummary: 'Lock and Love Moto Jacket is rated 4.3/5 from 2,700 reviews. Chic styling with soft realistic faux leather.',
  },
  {
    id: 'prod_fs_17',
    name: "Rain Jacket Women Windbreaker Striped Climbing Hooded Raincoat",
    brand: 'OutdoorPeak',
    category: 'Footwear',
    price: 339900,
    displayPrice: 3399,
    originalPrice: 4499,
    discountPercent: 24,
    rating: 4.4,
    reviewsCount: 5432,
    inStock: true,
    stockCount: 45,
    badge: 'Best Seller',
    description: 'Lightweight waterproof raincoat with striped cotton lining, adjustable drawstring waist and hood.',
    specs: ['Waterproof Breathable Fabric', 'Striped Soft Cotton Interior', 'Packable Lightweight Design', 'Deep Utility Flap Pockets'],
    imageUrl: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png',
    priceBand: 'mid',
    reviewSummary: 'Rain Jacket Women Windbreaker has 4.4/5 stars from 5,400+ reviews. Lightweight, stylish, and completely rainproof.',
  },
  {
    id: 'prod_fs_18',
    name: "MBJ Women's Solid Short Sleeve Boat Neck V-Cut Top",
    brand: 'MBJ',
    category: 'Footwear',
    price: 84900,
    displayPrice: 849,
    originalPrice: 1199,
    discountPercent: 29,
    rating: 4.7,
    reviewsCount: 1040,
    inStock: true,
    stockCount: 65,
    badge: 'Comfort Pick',
    description: 'Lightweight stretch fabric for casual comfort, ribbed on sleeves and neckline with double stitching on bottom hem.',
    specs: ['95% Rayon / 5% Spandex', 'Silky Breathable Drape', 'Boat Neckline with V Detail', 'Easy Care Wash'],
    imageUrl: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png',
    priceBand: 'budget',
    reviewSummary: 'MBJ Solid Short Sleeve Top has 4.7/5 stars from 1,000+ customers. Incredibly soft, flattering fit for everyday wear.',
  },
];

export const DUMMYJSON_PRODUCTS: CatalogProduct[] = [
  {
    id: 'prod_dj_1',
    name: 'Essence Mascara Lash Princess Volumizing Formula',
    brand: 'Essence',
    category: 'Wearables',
    price: 84900,
    displayPrice: 849,
    originalPrice: 1099,
    discountPercent: 23,
    rating: 4.6,
    reviewsCount: 420,
    inStock: true,
    stockCount: 99,
    badge: 'Best Seller',
    description: 'Achieve dramatic lashes with this long-lasting, cruelty-free volumizing and lengthening mascara.',
    specs: ['Cruelty-Free & Vegan', 'Conical Shape Fiber Brush', 'Smudge-Proof All Day Wear', 'Ophthalmologist Tested'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp',
    priceBand: 'budget',
    reviewSummary: 'Essence Lash Princess Mascara has 4.6/5 stars. World-famous for dramatic false-lash volume without clumping.',
  },
  {
    id: 'prod_dj_2',
    name: 'Glamour Beauty Eyeshadow Palette with Mirror (18 Shades)',
    brand: 'Glamour Beauty',
    category: 'Wearables',
    price: 169900,
    displayPrice: 1699,
    originalPrice: 2199,
    discountPercent: 23,
    rating: 4.4,
    reviewsCount: 310,
    inStock: true,
    stockCount: 34,
    badge: 'Popular',
    description: 'Versatile range of 18 rich matte and shimmer eyeshadow shades with a built-in large mirror.',
    specs: ['18 Highly Pigmented Shades', 'Matte, Shimmer & Glitter Finishes', 'Full Size Built-in Mirror', 'Blendable Long-wear Formula'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp',
    priceBand: 'budget',
    reviewSummary: 'Glamour Eyeshadow Palette has 4.4/5 stars. Great buttery pigment and versatile shades for day and night looks.',
  },
  {
    id: 'prod_dj_6',
    name: 'Calvin Klein CK One Unisex Eau De Toilette (100ml)',
    brand: 'Calvin Klein',
    category: 'Wearables',
    price: 424900,
    displayPrice: 4249,
    originalPrice: 5499,
    discountPercent: 23,
    rating: 4.8,
    reviewsCount: 890,
    inStock: true,
    stockCount: 29,
    badge: 'Iconic Classic',
    description: 'CK One is a classic unisex fragrance featuring refreshing notes of green tea, bergamot, cardamom, and musk.',
    specs: ['100ml Eau De Toilette Spray', 'Top Notes: Bergamot, Pineapple, Cardamom', 'Heart: Jasmine, Rose, Nutmeg', 'Base: Amber, Musk, Sandalwood'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp',
    priceBand: 'mid',
    reviewSummary: 'Calvin Klein CK One is rated 4.8/5 by 890 reviewers. Timeless, clean, fresh unisex scent for daily office and casual wear.',
  },
  {
    id: 'prod_dj_7',
    name: 'Chanel Coco Noir Eau De Parfum Spray (100ml)',
    brand: 'Chanel',
    category: 'Wearables',
    price: 1099900,
    displayPrice: 10999,
    originalPrice: 13999,
    discountPercent: 21,
    rating: 4.9,
    reviewsCount: 650,
    inStock: true,
    stockCount: 18,
    badge: 'Luxury Signature',
    description: 'Coco Noir by Chanel is an elegant, luminous oriental fragrance with grapefruit, rose, patchouli, and bourbon vanilla.',
    specs: ['100ml Eau De Parfum', 'Top: Grapefruit, Bergamot', 'Heart: Rose, Jasmine, Narcissus', 'Base: Patchouli, Sandalwood, Bourbon Vanilla'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp',
    priceBand: 'premium',
    reviewSummary: 'Chanel Coco Noir is rated 4.9/5 by 650 perfume enthusiasts. Deeply seductive, opulent, and long-lasting luxury sillage.',
  },
  {
    id: 'prod_dj_8',
    name: "Dior J'adore Eau De Parfum Floral Fragrance (100ml)",
    brand: 'Dior',
    category: 'Wearables',
    price: 764900,
    displayPrice: 7649,
    originalPrice: 9499,
    discountPercent: 19,
    rating: 4.8,
    reviewsCount: 920,
    inStock: true,
    stockCount: 25,
    badge: 'Best Seller',
    description: "J'adore by Dior is a golden floral bouquet combining ylang-ylang, Damascus rose, and Grasse jasmine.",
    specs: ['100ml Eau De Parfum', 'Floral Masterpiece', 'Notes: Ylang-Ylang, Damascus Rose, Jasmine', 'Iconic Amphora Bottle'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/fragrances/dior-j\'adore/1.webp',
    priceBand: 'mid',
    reviewSummary: "Dior J'adore has 4.8/5 stars across 900+ reviews. A grand floral classic praised for elegance and all-day projection.",
  },
  {
    id: 'prod_dj_14',
    name: 'Knoll Saarinen Executive Ergonomic Conference Chair',
    brand: 'Knoll',
    category: 'Peripherals',
    price: 4249900,
    displayPrice: 42499,
    originalPrice: 49999,
    discountPercent: 15,
    rating: 4.9,
    reviewsCount: 380,
    inStock: true,
    stockCount: 12,
    badge: 'Designer Classic',
    description: 'The Knoll Saarinen Executive Chair is a timeless mid-century ergonomic chair designed for premium executive workspaces.',
    specs: ['Molded Reinforced Polyurethane Shell', 'Premium Wool Blend Upholstery', 'Pneumatic Height Adjustment', 'Polished Aluminum Swivel Base'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp',
    priceBand: 'premium',
    reviewSummary: 'Knoll Saarinen Executive Chair is rated 4.9/5 stars. Iconic design meeting supreme ergonomic support for all-day focus.',
  },
  {
    id: 'prod_dj_47',
    name: 'Nordic Minimalist Smart LED Table Lamp with Touch Dimming',
    brand: 'Lumora',
    category: 'Peripherals',
    price: 424900,
    displayPrice: 4249,
    originalPrice: 5499,
    discountPercent: 23,
    rating: 4.6,
    reviewsCount: 540,
    inStock: true,
    stockCount: 45,
    badge: 'Trending',
    description: 'Modern minimalist table lamp providing glare-free ambient and task lighting with 3 color temperatures and touch dimming.',
    specs: ['3 Color Temperatures (3000K-6000K)', 'Stepless Touch Dimming', 'Flicker-Free Eye Protection LED', 'USB-C Rechargeable Base'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/home-decoration/table-lamp/1.webp',
    priceBand: 'mid',
    reviewSummary: 'Nordic Minimalist LED Lamp is rated 4.6/5 stars by 540 buyers for stylish modern design and eye-friendly soft lighting.',
  },
  {
    id: 'prod_dj_51',
    name: 'NutriPro Multi-Function Boxed Countertop Blender (1000W)',
    brand: 'NutriPro',
    category: 'Gaming',
    price: 339900,
    displayPrice: 3399,
    originalPrice: 4499,
    discountPercent: 24,
    rating: 4.6,
    reviewsCount: 780,
    inStock: true,
    stockCount: 20,
    badge: 'Best Seller',
    description: 'Powerful 1000W countertop blender for silky smoothies, protein shakes, nut butters, and frozen ice drinks.',
    specs: ['1000W High-Torque Pure Copper Motor', '6-Blade Stainless Steel Vortex Extractor', 'Includes 2 BPA-Free To-Go Cups', 'Pulse & 3-Speed Presets'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/1.webp',
    priceBand: 'mid',
    reviewSummary: 'NutriPro 1000W Blender has 4.6/5 stars from 780 customers. Crushes frozen fruits and ice smoothly in under 15 seconds.',
  },
  {
    id: 'prod_dj_61',
    name: 'ChefMaster Multi-Speed Immersion Hand Blender (600W)',
    brand: 'ChefMaster',
    category: 'Gaming',
    price: 299900,
    displayPrice: 2999,
    originalPrice: 3999,
    discountPercent: 25,
    rating: 4.5,
    reviewsCount: 620,
    inStock: true,
    stockCount: 40,
    badge: 'Great Value',
    description: 'Versatile 600W stainless steel stick immersion blender with whisk and chopper attachments for soups and purees.',
    specs: ['600W DC Motor with Turbo Boost', 'Detachable Stainless Steel Blending Wand', 'Includes Whisk & 500ml Chopper Bowl', 'Ergonomic Non-Slip Grip'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/1.webp',
    priceBand: 'mid',
    reviewSummary: 'ChefMaster Hand Blender is rated 4.5/5 by 620 home chefs. Powerful, compact, and very easy to wash.',
  },
  {
    id: 'prod_dj_78',
    name: 'Apple MacBook Pro 14" M3 Chip (16GB RAM / 512GB SSD)',
    brand: 'Apple',
    category: 'Peripherals',
    price: 14999900,
    displayPrice: 149999,
    originalPrice: 169900,
    discountPercent: 12,
    rating: 4.9,
    reviewsCount: 1420,
    inStock: true,
    stockCount: 15,
    badge: 'Pro Flagship',
    description: 'Unleash extreme pro workflows with the Apple M3 chip, Liquid Retina XDR display, and up to 22 hours of battery life.',
    specs: ['Apple M3 8-Core CPU / 10-Core GPU', '14.2" Liquid Retina XDR (120Hz ProMotion)', '16GB Unified Memory / 512GB SSD', 'MagSafe 3, HDMI, SDXC, 3x Thunderbolt 4'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14/1.webp',
    priceBand: 'premium',
    reviewSummary: 'Apple MacBook Pro 14" M3 is rated 4.9/5 by 1,400+ pro users. Unmatched battery life, astonishing performance, and best-in-class display.',
  },
  {
    id: 'prod_dj_79',
    name: 'Dell XPS 13 InfinityEdge Ultrabook (Intel Core i7 / 16GB / 512GB)',
    brand: 'Dell',
    category: 'Peripherals',
    price: 9999900,
    displayPrice: 99999,
    originalPrice: 119999,
    discountPercent: 17,
    rating: 4.7,
    reviewsCount: 890,
    inStock: true,
    stockCount: 18,
    badge: 'Top Pick',
    description: 'Crafted from machined aluminum and carbon fiber with a 13.4" FHD+ 500-nit InfinityEdge display.',
    specs: ['Intel Core i7-1360P 12-Core', '13.4" FHD+ (1920x1200) 500-nit Display', '16GB LPDDR5 / 512GB PCIe NVMe SSD', 'Backlit Keyboard with Fingerprint Reader'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/laptops/dell-xps-13/1.webp',
    priceBand: 'premium',
    reviewSummary: 'Dell XPS 13 is rated 4.7/5 stars. Stunning bezel-less screen and ultra-lightweight portability for business professionals.',
  },
  {
    id: 'prod_dj_83',
    name: 'Apple iPhone 15 Pro Max (256GB Titanium Natural)',
    brand: 'Apple',
    category: 'Wearables',
    price: 13499900,
    displayPrice: 134999,
    originalPrice: 154900,
    discountPercent: 13,
    rating: 4.9,
    reviewsCount: 2850,
    inStock: true,
    stockCount: 22,
    badge: 'Flagship Phone',
    description: 'Forged in aerospace-grade titanium with the A17 Pro chip, Action button, and 48MP 5x optical telephoto camera system.',
    specs: ['6.7" Super Retina XDR with ProMotion', 'A17 Pro Chip with 6-Core GPU', '48MP Main Camera + 5x Telephoto Zoom', 'USB-C with USB 3 Speeds (10Gbps)'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/smartphones/iphone-15-pro-max/1.webp',
    priceBand: 'premium',
    reviewSummary: 'iPhone 15 Pro Max is rated 4.9/5 by 2,800+ buyers. Incredible titanium build, 5x telephoto camera, and console-grade gaming graphics.',
  },
  {
    id: 'prod_dj_84',
    name: 'Samsung Galaxy S24 Ultra 5G AI Smartphone (256GB Titanium Gray)',
    brand: 'Samsung',
    category: 'Wearables',
    price: 11999900,
    displayPrice: 119999,
    originalPrice: 134999,
    discountPercent: 11,
    rating: 4.8,
    reviewsCount: 2100,
    inStock: true,
    stockCount: 25,
    badge: 'AI Flagship',
    description: 'Galaxy AI smartphone with built-in S Pen, 200MP camera, Snapdragon 8 Gen 3, and flat 6.8" 2600-nit Dynamic AMOLED 2X.',
    specs: ['6.8" QHD+ Dynamic AMOLED 2X (2600 nits)', '200MP Quad Camera with 100x Space Zoom', 'Integrated S Pen Stylus', 'Galaxy AI Live Translate & Circle to Search'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s24-ultra/1.webp',
    priceBand: 'premium',
    reviewSummary: 'Samsung Galaxy S24 Ultra is rated 4.8/5 by 2,100 users. Unsurpassed zoom photography, anti-reflective display, and Galaxy AI productivity.',
  },
  {
    id: 'prod_dj_88',
    name: 'Nike Air Jordan 1 Retro High OG Chicago Sneakers',
    brand: 'Nike',
    category: 'Footwear',
    price: 1499500,
    displayPrice: 14995,
    originalPrice: 17995,
    discountPercent: 17,
    rating: 4.9,
    reviewsCount: 3450,
    inStock: true,
    stockCount: 16,
    badge: 'Collector Edition',
    description: 'The iconic 1985 silhouette that changed basketball and sneaker culture forever. Premium full-grain leather in Varsity Red & White.',
    specs: ['Full-Grain Leather Upper', 'Encapsulated Air-Sole Cushioning', 'Solid Rubber Outsole with Deep Flex Grooves', 'Includes Extra White & Red Laces'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-retro-high/1.webp',
    priceBand: 'premium',
    reviewSummary: 'Air Jordan 1 Retro High OG is rated 4.9/5 by 3,400+ sneakerheads. Pure heritage design with top-tier premium leather quality.',
  },
  {
    id: 'prod_dj_89',
    name: 'Puma Velocity Nitro 2 Running Shoes with NITRO Foam',
    brand: 'Puma',
    category: 'Footwear',
    price: 699900,
    displayPrice: 6999,
    originalPrice: 9999,
    discountPercent: 30,
    rating: 4.7,
    reviewsCount: 1280,
    inStock: true,
    stockCount: 32,
    badge: 'Best Value Runner',
    description: 'All-in-one neutral running shoe with NITRO FOAM for responsive cushioning and PUMAGRIP all-surface traction outsole.',
    specs: ['Advanced NITRO FOAM Nitrogen-Infused Cushioning', 'PUMAGRIP High-Traction Rubber Outsole', 'Engineered Mesh Upper with TPU Heel Clip', 'Weight: 257g (Men size UK 8)'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-velocity-nitro-2/1.webp',
    priceBand: 'mid',
    reviewSummary: 'Puma Velocity Nitro 2 is rated 4.7/5 stars. Incredibly responsive, lightweight daily trainer offering superior grip on wet tarmac.',
  },
  {
    id: 'prod_dj_94',
    name: 'Rolex Submariner Date 41mm Oystersteel Automatic Luxury Watch',
    brand: 'Rolex',
    category: 'Wearables',
    price: 84999900,
    displayPrice: 849999,
    originalPrice: 999999,
    discountPercent: 15,
    rating: 5.0,
    reviewsCount: 820,
    inStock: true,
    stockCount: 4,
    badge: 'Grail Luxury',
    description: 'The benchmark among divers watches. Oystersteel with black Cerachrom bezel and large luminescent Chromalight hour markers.',
    specs: ['41mm Oystersteel Monobloc Case', 'Calibre 3235 Self-Winding Movement (70h Power Reserve)', 'Unidirectional 60-Minute Cerachrom Bezel', 'Waterproof to 300 meters / 1,000 feet'],
    imageUrl: 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-date/1.webp',
    priceBand: 'premium',
    reviewSummary: 'Rolex Submariner Date has a perfect 5.0/5 rating from horology collectors. The quintessential luxury sports watch built to last generations.',
  },
];
