export interface CatalogProduct {
  id: string;
  name: string;
  description: string;
  price: number;            // price in paise (₹1 = 100 paise)
  displayPrice: number;     // price in rupees (e.g., 2499)
  originalPrice: number;    // original MRP in rupees (e.g., 4999)
  discountPercent: number;  // e.g. 50
  category: 'Audio' | 'Peripherals' | 'Wearables' | 'Storage' | 'Gaming' | 'Accessories';
  rating: number;           // e.g. 4.6
  reviewCount: number;      // e.g. 1420
  badge?: 'Best Seller' | "Amazon's Choice" | 'Limited Deal' | 'Trending';
  primeEligible: boolean;
  imageUrl: string;
  inStock: boolean;
  features: string[];
}

export const PRODUCTS_CATALOG: CatalogProduct[] = [
  {
    id: 'prod_earbuds_pro',
    name: 'AuraPods Pro Active Noise Cancelling Earbuds',
    description: 'True wireless earbuds with 35dB Hybrid ANC, 40-hour total battery, Quad-mic AI call clarity, and IPX5 sweat resistance.',
    price: 249900,
    displayPrice: 2499,
    originalPrice: 4999,
    discountPercent: 50,
    category: 'Audio',
    rating: 4.8,
    reviewCount: 3840,
    badge: 'Best Seller',
    primeEligible: true,
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    features: ['Active Noise Cancellation', '40H Battery Life', 'Fast Wireless Charging', 'Bluetooth 5.3'],
  },
  {
    id: 'prod_keyboard_rgb',
    name: 'CyberMech RGB Mechanical Gaming Keyboard',
    description: 'Full-size mechanical keyboard with hot-swappable tactile switches, dynamic per-key RGB backlighting, and CNC aluminum top plate.',
    price: 399900,
    displayPrice: 3999,
    originalPrice: 6999,
    discountPercent: 43,
    category: 'Peripherals',
    rating: 4.7,
    reviewCount: 2190,
    badge: "Amazon's Choice",
    primeEligible: true,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    features: ['Hot-swappable Switches', 'RGB Backlight', 'Detachable Type-C Cable', 'Anti-Ghosting Keys'],
  },
  {
    id: 'prod_smartwatch',
    name: 'PulseTrack Ultra AMOLED Smartwatch',
    description: '1.96" Ultra AMOLED curved display, real-time SpO2 & Heart Rate monitoring, Bluetooth calling, GPS tracking, and 10-day battery.',
    price: 449900,
    displayPrice: 4499,
    originalPrice: 8999,
    discountPercent: 50,
    category: 'Wearables',
    rating: 4.6,
    reviewCount: 4120,
    badge: 'Limited Deal',
    primeEligible: true,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    features: ['1.96" AMOLED Display', 'BT Calling & Notifications', '100+ Sports Modes', '10-Day Battery Life'],
  },
  {
    id: 'prod_ssd_1tb',
    name: 'TurboDrive NVMe 1TB Portable SSD',
    description: 'High-speed external solid state drive with up to 1050MB/s transfer speeds, drop-resistant shockproof casing, and USB-C 3.2 Gen 2.',
    price: 549900,
    displayPrice: 5499,
    originalPrice: 8499,
    discountPercent: 35,
    category: 'Storage',
    rating: 4.9,
    reviewCount: 1870,
    badge: "Amazon's Choice",
    primeEligible: true,
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    features: ['1050 MB/s Read Speed', 'Shock & Drop Resistant', 'Hardware Encryption', 'Includes USB-C & USB-A cables'],
  },
  {
    id: 'prod_usbc_hub',
    name: 'AeroPort 7-in-1 Aluminium USB-C Hub',
    description: 'Multiport adapter featuring 4K@60Hz HDMI, 100W Power Delivery pass-through, 3x USB 3.0 ports, and SD/TF card reader slots.',
    price: 179900,
    displayPrice: 1799,
    originalPrice: 3299,
    discountPercent: 45,
    category: 'Accessories',
    rating: 4.5,
    reviewCount: 950,
    badge: 'Trending',
    primeEligible: true,
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    features: ['4K HDMI Output', '100W Fast Power Delivery', 'High Speed 5Gbps USB 3.0', 'Universal Compatibility'],
  },
  {
    id: 'prod_webcam_4k',
    name: 'VisionClear 4K Ultra HD Streaming Webcam',
    description: 'Professional 4K streaming camera with AI autofocus, dual noise-cancelling microphones, automatic low-light correction, and privacy shutter.',
    price: 329900,
    displayPrice: 3299,
    originalPrice: 5999,
    discountPercent: 45,
    category: 'Peripherals',
    rating: 4.7,
    reviewCount: 1320,
    badge: 'Trending',
    primeEligible: true,
    imageUrl: 'https://images.unsplash.com/photo-1588702547919-26089e690ecc?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    features: ['4K 30fps / 1080p 60fps', 'AI Auto-Focus & Framing', 'Dual Stereo Mics', 'Physical Privacy Shutter'],
  },
  {
    id: 'prod_gaming_mouse',
    name: 'ViperStrike Wireless Gaming Mouse (26K DPI)',
    description: 'Ultralight 58g wireless mouse with optical switches, 26,000 DPI sensor, 0.2ms response time, and 90-hour battery life.',
    price: 219900,
    displayPrice: 2199,
    originalPrice: 3999,
    discountPercent: 45,
    category: 'Gaming',
    rating: 4.8,
    reviewCount: 2890,
    badge: 'Best Seller',
    primeEligible: true,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    features: ['58g Ultralight Shell', '26K Optical Sensor', '90 Hours Battery', 'PTFE Pure Glide Skates'],
  },
  {
    id: 'prod_headphones_anc',
    name: 'SoundAura Max Wireless Over-Ear Headphones',
    description: 'Studio-grade Hi-Res certified headphones with 45mm custom dynamic drivers, Hybrid Active Noise Cancellation, and 60-hour playtime.',
    price: 499900,
    displayPrice: 4999,
    originalPrice: 9999,
    discountPercent: 50,
    category: 'Audio',
    rating: 4.9,
    reviewCount: 5200,
    badge: "Amazon's Choice",
    primeEligible: true,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    features: ['Hi-Res Audio Certified', 'Hybrid ANC with Ambient Mode', '60-Hour Playtime', 'Plush Memory Foam Earcups'],
  },
  {
    id: 'prod_charging_station',
    name: 'MagPower 3-in-1 Magnetic Wireless Stand',
    description: '15W fast wireless charging station for Smartphone, Smartwatch, and Wireless Earbuds simultaneously with angle adjustment.',
    price: 189900,
    displayPrice: 1899,
    originalPrice: 3499,
    discountPercent: 46,
    category: 'Accessories',
    rating: 4.6,
    reviewCount: 1640,
    badge: 'Limited Deal',
    primeEligible: true,
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    features: ['Charges 3 Devices Simultaneously', '15W Fast Magnetic Charging', 'Foldable Travel Friendly', 'Overheat Protection'],
  },
];
