export interface CatalogProduct {
  id: string;
  name: string;
  brand: string;
  category: 'Audio' | 'Peripherals' | 'Wearables' | 'Storage' | 'Gaming' | 'Footwear';
  price: number; // in paise
  displayPrice: number; // in Rupees
  originalPrice: number; // in Rupees
  discountPercent: number;
  rating: number;
  reviewsCount: number;
  inStock: boolean;
  stockCount: number;
  badge?: string;
  description: string;
  specs: string[];
  imageUrl: string;
  priceBand: 'budget' | 'mid' | 'premium';
  /** Pre-written TTS-friendly review summary (optional — generated on-the-fly if missing) */
  reviewSummary?: string;
}

export const CATEGORIES = [
  'All Categories',
  'Audio',
  'Peripherals',
  'Wearables',
  'Storage',
  'Gaming',
  'Footwear',
] as const;

export const PRICE_BANDS = {
  budget: { label: 'Budget (Under ₹2,000)', min: 0, max: 2000 },
  mid: { label: 'Mid-Range (₹2,000 – ₹8,000)', min: 2000, max: 8000 },
  premium: { label: 'Premium (Over ₹8,000)', min: 8000, max: 1000000 },
};

import { FAKESTORE_PRODUCTS, DUMMYJSON_PRODUCTS } from './importedProducts';

const BASE_PRODUCTS: CatalogProduct[] = [
  // ==========================================
  // 1. AUDIO (₹499 - ₹19,990)
  // ==========================================
  {
    id: 'prod_boat_bassheads',
    name: 'boAt BassHeads 100 Wired Earphones with Mic',
    brand: 'boAt',
    category: 'Audio',
    price: 49900,
    displayPrice: 499,
    originalPrice: 999,
    discountPercent: 50,
    rating: 4.3,
    reviewsCount: 14200,
    inStock: true,
    stockCount: 85,
    badge: 'Best Seller',
    description: 'Super extra bass with 10mm dynamic drivers and in-line microphone.',
    specs: ['10mm Drivers', 'In-line HD Mic', 'Tangle-Free Cable', '3.5mm Jack'],
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'prod_boat_airdopes_141',
    name: 'boAt Airdopes 141 True Wireless Earbuds',
    brand: 'boAt',
    category: 'Audio',
    price: 129900,
    displayPrice: 1299,
    originalPrice: 2990,
    discountPercent: 57,
    rating: 4.4,
    reviewsCount: 8900,
    inStock: true,
    stockCount: 60,
    badge: 'Popular',
    description: '42H playtime with ENx noise cancellation technology and ASAP charge.',
    specs: ['42H Total Playtime', 'ENx Tech Mic', 'ASAP Charge', 'IPX4 Water Resistant'],
    imageUrl: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'prod_earbuds_pro',
    name: 'AuraPods Pro Active Noise Cancelling Earbuds',
    brand: 'Aura',
    category: 'Audio',
    price: 249900,
    displayPrice: 2499,
    originalPrice: 4999,
    discountPercent: 50,
    rating: 4.8,
    reviewsCount: 3840,
    inStock: true,
    stockCount: 45,
    badge: 'Amazon\'s Choice',
    description: 'Premium wireless earbuds with hybrid ANC up to 35dB and ultra-low latency game mode.',
    specs: ['35dB Hybrid ANC', '40H Battery Life', 'Bluetooth 5.3', 'Wireless Charging Case'],
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_jbl_tune_760nc',
    name: 'JBL Tune 760NC Wireless Over-Ear ANC Headphones',
    brand: 'JBL',
    category: 'Audio',
    price: 549900,
    displayPrice: 5499,
    originalPrice: 7999,
    discountPercent: 31,
    rating: 4.6,
    reviewsCount: 4200,
    inStock: true,
    stockCount: 30,
    badge: 'Trending',
    description: 'Punchy Pure Bass Sound with active noise cancellation and multi-point connectivity.',
    specs: ['Active Noise Cancelling', 'JBL Pure Bass', '50H Battery Life', 'Multi-Point Connection'],
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_sony_wh1000xm4',
    name: 'Sony WH-1000XM4 Industry Leading Wireless ANC Headphones',
    brand: 'Sony',
    category: 'Audio',
    price: 1999000,
    displayPrice: 19990,
    originalPrice: 29990,
    discountPercent: 33,
    rating: 4.9,
    reviewsCount: 9600,
    inStock: true,
    stockCount: 20,
    badge: 'Top Rated',
    description: 'Industry-leading noise canceling with Dual Noise Sensor technology and Speak-to-Chat.',
    specs: ['Dual Noise Sensor ANC', '30H Battery Life', 'LDAC Hi-Res Audio', 'Touch Sensor Controls'],
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    priceBand: 'premium',
  },
  {
    id: 'prod_bose_quietcomfort',
    name: 'Bose QuietComfort 45 Bluetooth Wireless Headphones',
    brand: 'Bose',
    category: 'Audio',
    price: 2490000,
    displayPrice: 24900,
    originalPrice: 29900,
    discountPercent: 17,
    rating: 4.8,
    reviewsCount: 3100,
    inStock: true,
    stockCount: 15,
    badge: 'Premium Pick',
    description: 'Iconic quiet, comfort, and sound with TriPort acoustic architecture.',
    specs: ['World-Class ANC', 'Quiet & Aware Modes', '24H Battery', 'Plush Synthetic Leather'],
    imageUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&auto=format&fit=crop&q=80',
    priceBand: 'premium',
  },

  // ==========================================
  // 2. PERIPHERALS (₹699 - ₹14,999)
  // ==========================================
  {
    id: 'prod_dell_wireless_mouse',
    name: 'Dell WM126 Optical Wireless Mouse (Black)',
    brand: 'Dell',
    category: 'Peripherals',
    price: 69900,
    displayPrice: 699,
    originalPrice: 1199,
    discountPercent: 42,
    rating: 4.3,
    reviewsCount: 18400,
    inStock: true,
    stockCount: 90,
    badge: 'Best Seller',
    description: 'Reliable wireless connectivity with 1000 DPI optical sensor and up to 1-year battery life.',
    specs: ['2.4GHz Plug & Play', '1000 DPI Sensor', '1-Year Battery', 'Comfortable Grip'],
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'prod_logitech_k380',
    name: 'Logitech K380 Multi-Device Bluetooth Keyboard',
    brand: 'Logitech',
    category: 'Peripherals',
    price: 269500,
    displayPrice: 2695,
    originalPrice: 3295,
    discountPercent: 18,
    rating: 4.7,
    reviewsCount: 6500,
    inStock: true,
    stockCount: 40,
    badge: 'Amazon\'s Choice',
    description: 'Compact wireless keyboard that connects to up to 3 devices with easy-switch buttons.',
    specs: ['Easy-Switch 3 Devices', '2-Year Battery Life', 'Quiet Low-Profile Keys', 'Mac & Windows Compatible'],
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_keyboard_rgb',
    name: 'CyberMech RGB Mechanical Gaming Keyboard',
    brand: 'CyberMech',
    category: 'Peripherals',
    price: 399900,
    displayPrice: 3999,
    originalPrice: 6999,
    discountPercent: 43,
    rating: 4.7,
    reviewsCount: 2190,
    inStock: true,
    stockCount: 30,
    badge: 'Hot Deal',
    description: '75% compact layout with hot-swappable tactile switches and per-key RGB backlighting.',
    specs: ['Hot-swappable Switches', '75% Compact Layout', 'RGB Backlit (18 Modes)', 'PBT Double-shot Keycaps'],
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_logitech_mx_master_3s',
    name: 'Logitech MX Master 3S Wireless Performance Mouse',
    brand: 'Logitech',
    category: 'Peripherals',
    price: 899500,
    displayPrice: 8995,
    originalPrice: 10995,
    discountPercent: 18,
    rating: 4.9,
    reviewsCount: 5400,
    inStock: true,
    stockCount: 25,
    badge: 'Pro Choice',
    description: 'Quiet clicks and 8K DPI any-surface tracking with electromagnetic MagSpeed scrolling.',
    specs: ['8K DPI Darkfield Sensor', 'MagSpeed SmartScroll', 'Quiet Click Tech', 'USB-C Quick Charge'],
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
    priceBand: 'premium',
  },
  {
    id: 'prod_keychron_q1_pro',
    name: 'Keychron Q1 Pro Custom Wireless Mechanical Keyboard',
    brand: 'Keychron',
    category: 'Peripherals',
    price: 1499900,
    displayPrice: 14999,
    originalPrice: 18999,
    discountPercent: 21,
    rating: 4.9,
    reviewsCount: 1200,
    inStock: true,
    stockCount: 12,
    badge: 'Enthusiast',
    description: 'Full CNC machined aluminum body with double-gasket design, QMK/VIA programmable.',
    specs: ['Full Aluminum Body', 'Double Gasket Mount', 'QMK/VIA Programmable', 'K Pro Mechanical Switches'],
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    priceBand: 'premium',
  },

  // ==========================================
  // 3. WEARABLES (₹1,499 - ₹29,990)
  // ==========================================
  {
    id: 'prod_noise_colorfit_pulse',
    name: 'Noise ColorFit Pulse 2 Max 1.85" Smartwatch',
    brand: 'Noise',
    category: 'Wearables',
    price: 149900,
    displayPrice: 1499,
    originalPrice: 5999,
    discountPercent: 75,
    rating: 4.2,
    reviewsCount: 16500,
    inStock: true,
    stockCount: 75,
    badge: 'Budget Hero',
    description: 'Massive 1.85" bright TFT display with Bluetooth calling and 100 sports modes.',
    specs: ['1.85" LCD Display', 'Bluetooth Calling', '10-Day Battery', 'Heart Rate & SpO2'],
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'prod_smartwatch_ultra',
    name: 'PulseTrack Ultra AMOLED Fitness Smartwatch',
    brand: 'PulseTrack',
    category: 'Wearables',
    price: 449900,
    displayPrice: 4499,
    originalPrice: 8999,
    discountPercent: 50,
    rating: 4.6,
    reviewsCount: 4120,
    inStock: true,
    stockCount: 25,
    badge: 'Limited Deal',
    description: '1.96-inch HD AMOLED curved display with continuous SpO2, ECG monitoring, and IP68 rating.',
    specs: ['1.96" AMOLED Always-On', 'BT Calling & AI Voice', '120+ Sports Modes', '7-Day Battery Life'],
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_oneplus_watch_2',
    name: 'OnePlus Watch 2 with Dual Engine Architecture',
    brand: 'OnePlus',
    category: 'Wearables',
    price: 1999900,
    displayPrice: 19999,
    originalPrice: 24999,
    discountPercent: 20,
    rating: 4.7,
    reviewsCount: 2200,
    inStock: true,
    stockCount: 18,
    badge: 'Flagship',
    description: 'Powered by Wear OS by Google with Snapdragon W5 Gen 1 chipset and up to 100 hours battery.',
    specs: ['Wear OS by Google', '100H Smart Battery', 'Dual-Frequency GPS', 'Sapphire Crystal Glass'],
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    priceBand: 'premium',
  },
  {
    id: 'prod_samsung_galaxy_watch6',
    name: 'Samsung Galaxy Watch6 LTE (44mm, Graphite)',
    brand: 'Samsung',
    category: 'Wearables',
    price: 2499900,
    displayPrice: 24999,
    originalPrice: 33999,
    discountPercent: 26,
    rating: 4.8,
    reviewsCount: 3800,
    inStock: true,
    stockCount: 14,
    badge: 'Top Pick',
    description: 'Advanced sleep coaching, personalized HR zones, and sapphire crystal durability.',
    specs: ['Super AMOLED Display', 'LTE Standalone Calling', 'Body Composition BIA', 'Sleep Coaching'],
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    priceBand: 'premium',
  },
  {
    id: 'prod_apple_watch_se',
    name: 'Apple Watch SE (2nd Gen, GPS 40mm) Starlight',
    brand: 'Apple',
    category: 'Wearables',
    price: 2899000,
    displayPrice: 28990,
    originalPrice: 29900,
    discountPercent: 3,
    rating: 4.9,
    reviewsCount: 6700,
    inStock: true,
    stockCount: 10,
    badge: 'Apple Original',
    description: 'Essential health, fitness, and safety features with Crash Detection and Retina display.',
    specs: ['Retina Display 1000 nits', 'Crash & Fall Detection', 'Swimproof 50m', 'Heart Rate Notifications'],
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    priceBand: 'premium',
  },

  // ==========================================
  // 4. STORAGE (₹899 - ₹16,499)
  // ==========================================
  {
    id: 'prod_sandisk_cruzer_blade_128',
    name: 'SanDisk Ultra Dual 128GB USB 3.1 Flash Drive',
    brand: 'SanDisk',
    category: 'Storage',
    price: 89900,
    displayPrice: 899,
    originalPrice: 1600,
    discountPercent: 44,
    rating: 4.5,
    reviewsCount: 34000,
    inStock: true,
    stockCount: 120,
    badge: 'Best Seller',
    description: 'High-speed USB 3.1 performance up to 150MB/s with USB Type-C and Type-A connectors.',
    specs: ['128GB Storage', '150 MB/s Read Speed', 'Dual Type-C & Type-A', 'SanDisk Memory Zone App'],
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'prod_crucial_p3_1tb',
    name: 'Crucial P3 1TB PCIe 3.0 3D NAND NVMe M.2 SSD',
    brand: 'Crucial',
    category: 'Storage',
    price: 499900,
    displayPrice: 4999,
    originalPrice: 8500,
    discountPercent: 41,
    rating: 4.7,
    reviewsCount: 8900,
    inStock: true,
    stockCount: 40,
    badge: 'Popular',
    description: 'Sequential read speeds up to 3500MB/s for super-fast OS booting and game loading.',
    specs: ['1TB NVMe M.2 2280', 'Up to 3500MB/s Speed', 'Micron 3D NAND', '5-Year Warranty'],
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_ssd_portable_1tb',
    name: 'TurboDrive NVMe 1TB Portable External SSD',
    brand: 'TurboDrive',
    category: 'Storage',
    price: 549900,
    displayPrice: 5499,
    originalPrice: 8499,
    discountPercent: 35,
    rating: 4.9,
    reviewsCount: 1870,
    inStock: true,
    stockCount: 40,
    badge: 'Amazon\'s Choice',
    description: 'Super-fast 1050 MB/s read/write speeds in a pocket-sized drop-resistant aluminium casing.',
    specs: ['1050 MB/s Read Speed', 'Shock-Proof Rugged Shell', 'USB 3.2 Gen 2 Type-C', 'Mac, Windows & Android'],
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_samsung_t7_shield_2tb',
    name: 'Samsung T7 Shield 2TB Rugged Portable SSD (IP65)',
    brand: 'Samsung',
    category: 'Storage',
    price: 1549900,
    displayPrice: 15499,
    originalPrice: 24999,
    discountPercent: 38,
    rating: 4.9,
    reviewsCount: 5200,
    inStock: true,
    stockCount: 18,
    badge: 'Pro Grade',
    description: 'Extremely tough IP65 water/dust resistant external SSD with 1050MB/s speeds.',
    specs: ['2TB Storage', 'IP65 Water & Dust Resistant', '3-Meter Drop Resistance', 'Dynamic Thermal Guard'],
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&auto=format&fit=crop&q=80',
    priceBand: 'premium',
  },

  // ==========================================
  // 5. GAMING (₹1,299 - ₹24,999)
  // ==========================================
  {
    id: 'prod_cosmicbyte_gamepad',
    name: 'Cosmic Byte Ares Wireless Controller for PC & Android',
    brand: 'Cosmic Byte',
    category: 'Gaming',
    price: 149900,
    displayPrice: 1499,
    originalPrice: 2199,
    discountPercent: 32,
    rating: 4.4,
    reviewsCount: 8400,
    inStock: true,
    stockCount: 55,
    badge: 'Best Seller',
    description: 'Magnetic triggers with ultra-precise analog sticks and dual vibration feedback motors.',
    specs: ['2.4GHz Wireless', 'Magnetic Hall Triggers', 'Dual Vibration Motors', '12H Rechargeable Battery'],
    imageUrl: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'prod_gaming_mouse_wireless',
    name: 'ViperStrike Wireless Ultralight Gaming Mouse (26K DPI)',
    brand: 'ViperStrike',
    category: 'Gaming',
    price: 219900,
    displayPrice: 2199,
    originalPrice: 3999,
    discountPercent: 45,
    rating: 4.8,
    reviewsCount: 2890,
    inStock: true,
    stockCount: 35,
    badge: 'Hot Deal',
    description: '58g feather-light honeycomb shell with PAW3395 optical sensor and 100M click optical switches.',
    specs: ['58g Featherlight Body', '26,000 DPI Sensor', 'Nordic 52840 MCU', '80H Battery Life'],
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_hyperx_cloud_ii',
    name: 'HyperX Cloud II Pro Wireless Gaming Headset 7.1',
    brand: 'HyperX',
    category: 'Gaming',
    price: 799000,
    displayPrice: 7990,
    originalPrice: 13990,
    discountPercent: 43,
    rating: 4.8,
    reviewsCount: 9400,
    inStock: true,
    stockCount: 25,
    badge: 'Esports Standard',
    description: 'Legendary comfort with memory foam ear cushions and custom-tuned 53mm drivers.',
    specs: ['Virtual 7.1 Surround', '30H Wireless Range (20m)', '53mm Drivers', 'Detachable Noise-Canceling Mic'],
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_razer_blackwidow_v4',
    name: 'Razer BlackWidow V4 Pro Mechanical Gaming Keyboard',
    brand: 'Razer',
    category: 'Gaming',
    price: 1899900,
    displayPrice: 18999,
    originalPrice: 24999,
    discountPercent: 24,
    rating: 4.9,
    reviewsCount: 2100,
    inStock: true,
    stockCount: 15,
    badge: 'Flagship Gaming',
    description: 'Command dial and 8 dedicated macro keys with Chroma RGB underglow and magnetic wrist rest.',
    specs: ['Razer Green Clicky Switches', 'Razer Command Dial', '8000Hz Polling Rate', 'Magnetic Plush Wrist Rest'],
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    priceBand: 'premium',
  },

  // ==========================================
  // 6. FOOTWEAR & LIFESTYLE (₹1,199 - ₹12,999)
  // ==========================================
  {
    id: 'prod_sparx_running_shoes',
    name: 'Sparx Men SM-648 Lightweight Running Shoes',
    brand: 'Sparx',
    category: 'Footwear',
    price: 119900,
    displayPrice: 1199,
    originalPrice: 1899,
    discountPercent: 37,
    rating: 4.2,
    reviewsCount: 19800,
    inStock: true,
    stockCount: 100,
    badge: 'Best Seller',
    description: 'Breathable mesh upper with anti-skid EVA sole designed for daily jogging and gym sessions.',
    specs: ['Breathable Air Mesh', 'Anti-Skid EVA Sole', 'Padded Collar & Insole', 'Slip-Resistant Grip'],
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'prod_puma_smash_sneakers',
    name: 'Puma Unisex-Adult Smashic Low-Top Sneakers',
    brand: 'Puma',
    category: 'Footwear',
    price: 224900,
    displayPrice: 2249,
    originalPrice: 4499,
    discountPercent: 50,
    rating: 4.5,
    reviewsCount: 8200,
    inStock: true,
    stockCount: 50,
    badge: 'Trending',
    description: 'Classic tennis-inspired silhouette featuring SoftFoam+ comfort sockliner and durable rubber outsole.',
    specs: ['Synthetic Leather Upper', 'SoftFoam+ Cushioning', 'Durable Rubber Outsole', 'Lace-Up Fit'],
    imageUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_adidas_runfalcon_5',
    name: 'Adidas Men Runfalcon 5 Wide Breathable Running Shoes',
    brand: 'Adidas',
    category: 'Footwear',
    price: 349900,
    displayPrice: 3499,
    originalPrice: 5999,
    discountPercent: 42,
    rating: 4.6,
    reviewsCount: 6100,
    inStock: true,
    stockCount: 40,
    badge: 'Popular',
    description: 'Cloudfoam midsole delivers step-in comfort and superior cushioning for all-day road runs.',
    specs: ['Cloudfoam Midsole', 'Textile Upper Mesh', 'Adiwear Outsole', 'Eco-Friendly Recycled Materials'],
    imageUrl: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_asics_gel_contend_8',
    name: 'Asics Gel-Contend 8 Running Shoes with GEL Tech',
    brand: 'Asics',
    category: 'Footwear',
    price: 449900,
    displayPrice: 4499,
    originalPrice: 5999,
    discountPercent: 25,
    rating: 4.7,
    reviewsCount: 3900,
    inStock: true,
    stockCount: 30,
    badge: 'Amazon\'s Choice',
    description: 'Rearfoot GEL technology cushioning improves impact absorption and creates a softer feeling at footstrike.',
    specs: ['Rearfoot GEL Cushioning', 'AmpliFoam Midsole', 'Ortholite Sockliner', 'Guidance Line Outsole'],
    imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_nike_air_max_sc',
    name: 'Nike Men Air Max SC Leather & Mesh Sneakers',
    brand: 'Nike',
    category: 'Footwear',
    price: 599500,
    displayPrice: 5995,
    originalPrice: 7495,
    discountPercent: 20,
    rating: 4.8,
    reviewsCount: 5100,
    inStock: true,
    stockCount: 25,
    badge: 'Top Seller',
    description: 'Old-school track look with visible Max Air cushioning and durable leather upper.',
    specs: ['Visible Max Air Cushioning', 'Genuine Leather & Mesh', 'Rubber Waffle Outsole', 'Flex Grooves'],
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    priceBand: 'mid',
  },
  {
    id: 'prod_nike_pegasus_41',
    name: 'Nike Air Zoom Pegasus 41 Road Running Shoes',
    brand: 'Nike',
    category: 'Footwear',
    price: 1189500,
    displayPrice: 11895,
    originalPrice: 13995,
    discountPercent: 15,
    rating: 4.9,
    reviewsCount: 4400,
    inStock: true,
    stockCount: 15,
    badge: 'Elite Runner',
    description: 'Dual Air Zoom units with all-new ReactX foam midsole for 13% more energy return.',
    specs: ['ReactX Foam Midsole', 'Dual Air Zoom Units', 'Engineered Mesh Upper', 'Waffle Rubber Traction'],
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    priceBand: 'premium',
  },
  // ==========================================
  // 7. CROSS-SELL / ACCESSORY PRODUCTS
  // ==========================================
  {
    id: 'xsell_sports_socks',
    name: 'ProFit Cushioned Breathable Sports Socks (3-Pack)',
    brand: 'ProFit',
    category: 'Footwear',
    price: 34900,
    displayPrice: 349,
    originalPrice: 599,
    discountPercent: 42,
    rating: 4.6,
    reviewsCount: 1200,
    inStock: true,
    stockCount: 150,
    badge: 'Popular Add-On',
    description: 'High-cushion anti-blister moisture-wicking athletic running socks.',
    specs: ['Arch Support', 'Anti-Odor Mesh', 'Cushioned Heel & Toe', 'Dri-Fit Fabric'],
    imageUrl: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'xsell_carrying_case',
    name: 'AuraShield Shockproof Headphone Hard Travel Case',
    brand: 'Aura',
    category: 'Audio',
    price: 49900,
    displayPrice: 499,
    originalPrice: 999,
    discountPercent: 50,
    rating: 4.7,
    reviewsCount: 850,
    inStock: true,
    stockCount: 80,
    badge: 'Essential Accessory',
    description: 'EVA hard shell waterproof carrying case for over-ear headphones and earbuds.',
    specs: ['Shockproof EVA Shell', 'Soft Velvet Lining', 'Cable Storage Pocket', 'Heavy-Duty Zipper'],
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'xsell_wrist_rest',
    name: 'ErgoRest Memory Foam Keyboard & Mouse Wrist Rest',
    brand: 'ErgoRest',
    category: 'Peripherals',
    price: 39900,
    displayPrice: 399,
    originalPrice: 799,
    discountPercent: 50,
    rating: 4.5,
    reviewsCount: 920,
    inStock: true,
    stockCount: 110,
    badge: 'Ergonomic Choice',
    description: 'Non-slip ergonomic memory foam support for extended typing and gaming comfort.',
    specs: ['Slow-Rebound Memory Foam', 'Non-Skid Rubber Base', 'Ergonomic Contour', 'Breathable Lycra'],
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'xsell_watch_strap',
    name: 'QuickFit Magnetic Sport Silicone Smartwatch Strap',
    brand: 'QuickFit',
    category: 'Wearables',
    price: 44900,
    displayPrice: 449,
    originalPrice: 899,
    discountPercent: 50,
    rating: 4.6,
    reviewsCount: 1400,
    inStock: true,
    stockCount: 95,
    badge: 'Best Match',
    description: 'Sweatproof quick-release magnetic silicone replacement strap for smartwatches.',
    specs: ['Dual-Magnetic Clasp', 'Sweat & Water Resistant', 'Universal 20/22mm Pin', 'Silky Soft Finish'],
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'xsell_otg_cable',
    name: 'TurboSpeed Braided 10Gbps USB-C OTG Fast Cable',
    brand: 'TurboSpeed',
    category: 'Storage',
    price: 29900,
    displayPrice: 299,
    originalPrice: 599,
    discountPercent: 50,
    rating: 4.8,
    reviewsCount: 2100,
    inStock: true,
    stockCount: 200,
    badge: 'High Speed',
    description: 'High-speed plug-and-play adapter for laptops, tablets, and phones.',
    specs: ['10Gbps Transfer Rate', 'Nylon Braided Cable', 'Aluminum Alloy Shell', 'Universal USB-C'],
    imageUrl: 'https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
  {
    id: 'xsell_gaming_mousepad',
    name: 'HyperGlide Extended Anti-Fray RGB Gaming Mousepad',
    brand: 'HyperGlide',
    category: 'Gaming',
    price: 49900,
    displayPrice: 499,
    originalPrice: 999,
    discountPercent: 50,
    rating: 4.7,
    reviewsCount: 3100,
    inStock: true,
    stockCount: 120,
    badge: 'Gamer Essential',
    description: 'Smooth micro-woven cloth surface with stitched anti-fray edges and rubber grip base.',
    specs: ['Micro-Woven Cloth', 'Anti-Fray Stitched Edge', 'Non-Slip Rubber Base', 'Spill-Resistant'],
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
    priceBand: 'budget',
  },
];

/** Complete merged catalog with live data from FakeStoreAPI & DummyJSON */
export const PRODUCTS_CATALOG: CatalogProduct[] = [
  ...BASE_PRODUCTS,
  ...FAKESTORE_PRODUCTS,
  ...DUMMYJSON_PRODUCTS,
];

